Frama_C/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('frama_app/', include('frama_app.urls', namespace='frama_app')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

frama_app/urls.py
from django.urls import path
from django.contrib import admin

from . import views

app_name = 'frama_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('index', views.index, name='index'),
    path('login', views.login_page, name='login'),
    path('logout', views.logout_user, name='logout'),
    path('auth', views.auth, name='auth'),
    
    path('get/ajax/filetree', views.get_filetree, name='get_filetree'),
    path('get/ajax/file', views.get_file, name='file'),
    path('get/ajax/run', views.run_frama, name='run'),
    
    path('post/ajax/prover', views.change_prover, name='prover'),
    path('post/ajax/vcs', views.change_vcs, name='vcs'),
    path('post/ajax/add_dir', views.add_dir, name = 'add_dir'),
    path('post/ajax/add_file', views.add_file, name = 'add_file'),
    path('post/ajax/delete_node', views.delete_node, name = 'delete_node')
]

frama_app/models.py
import datetime

from django.db import models
from django.db.models import UniqueConstraint
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import AbstractUser


class Entity(models.Model):
    timestamp = models.DateTimeField(default=timezone.now)
    valid = models.BooleanField(default=True)

    class Meta:
        abstract = True

class User(AbstractUser):
    name = models.CharField( max_length=200)


class Node(Entity):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True, default='')
    date_created = models.DateField(auto_now=False, auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    parent = models.ForeignKey('Directory', on_delete=models.CASCADE, null=True, blank=True)
    exists = models.BooleanField(default=True)
    class Meta:
        abstract = True
    def __str__(self):
        return self.name
    def remove(self):
        self.exists = False
        self.save()
    def restore(self):
        self.exists = True
        self.save()
    @staticmethod
    def restore_all():
        for f in File.objects.filter(exists=False):
            f.restore()
        for d in Directory.objects.filter(exists=False):
            d.restore()

class Directory(Node):
    pass
    

class File(Node):
    file_object = models.FileField(null=True)
    frama_output = models.TextField(default='')
    

class StatusData(Entity):
    data = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)


class Section(Entity):
    class Category(models.TextChoices):
        REQUIRES = 'requires'
        ENSURES = 'ensures'
        VARIANT = 'variant'
        INVARIANT = 'invariant'
        PREDICATE = 'predicate'
        GHOST = 'ghost'
        ASSERT = 'assert'
        LEMMA = 'lemma'
        ASSIGNS = 'assigns'
        EXITS = 'exits'
        CHECK = 'check'
        BREAKS = 'breaks'
        CONTINUES = 'continues'
        RETURNS = 'returns'


    class Status(models.TextChoices):
        UNKNOWN = "lightgray"
        VALID = "mediumseagreen"
        FAILED = "red"
        TIMEOUT = "mediumslateblue"

    name = models.CharField(max_length=50, blank=True)
    description = models.TextField(blank=True)
    date_created = models.DateField(auto_now=False, auto_now_add=False)
    category = models.CharField(max_length=20,choices = Category.choices)
    status = models.CharField(max_length=20,choices = Status.choices, blank=True)
    status_data = models.ForeignKey(StatusData, on_delete=models.CASCADE, blank=True, null=True)
    file = models.ForeignKey(File, on_delete=models.CASCADE)
    line = models.IntegerField(default=0)
    
    def __str__(self):
        return str(self.category) + ', line ' + str(self.line)

frama_app/forms.py
from django.forms import ModelForm, ModelMultipleChoiceField, Form
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import *

class DirectoryForm(ModelForm):
    class Meta:
        model = Directory
        fields = ['name','description', 'parent']

class FileForm(ModelForm):
    class Meta:
        model = File
        fields = ['file_object', 'description', 'parent']

class DeletionForm(Form):
    files = ModelMultipleChoiceField(
        queryset = File.objects.filter(exists=True),
        widget = forms.CheckboxSelectMultiple(),
        to_field_name = "name",
        required = False
        )
    directories = ModelMultipleChoiceField(
        queryset = Directory.objects.filter(exists=True),
        widget = forms.CheckboxSelectMultiple(),
        to_field_name = "name",
        required = False
        )

class ProversForm(Form):
    CHOICES = [('alt-ergo', 'Alt-Ergo'), ('z3', 'Z3'), ('cvc4', 'CVC4')]
    prover = forms.CharField(label='Pick your prover', widget=forms.RadioSelect(choices=CHOICES), initial=CHOICES[0])
      

class VCsForm(Form):
    conditions = forms.MultipleChoiceField(
        label = 'Pick verification conditions',
        choices = Section.Category.choices,
        widget = forms.CheckboxSelectMultiple()
    )

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'name', 'password')


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'name', 'password')

    

frama_app/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from .forms import *
from .models import *
from django.urls import reverse
from django.utils import timezone
from django.db.models import Q
from django.db import IntegrityError
import os
from .frama import *
from django.contrib.auth import authenticate, login, logout

import json

empty_success = JsonResponse({}, status=200)
authentication_error = JsonResponse({"error": "not_authenticated"}, status=401)
bad_request = JsonResponse({"error": ""}, status=400)
forbidden = JsonResponse({"error": ""}, status=403)
not_found = JsonResponse({"error": ""}, status=404)
server_error = JsonResponse({"error": ""}, status=500)


def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect('/frama_app/login')

    context = {
        'add_file_form': FileForm(),
        'add_dir_form': DirectoryForm(),
        'delete_form': DeletionForm(),
        'provers_form': ProversForm(),
        'vcs_form': VCsForm()
    }

    return render(request, 'frama_app/index.html', context)


def add_dir(request):
    if not request.user or not request.user.is_authenticated:
        return authentication_error

    form = DirectoryForm(request.POST)
    form.instance.owner = request.user
    form.instance.date_created = timezone.now()
    if request.is_ajax and request.method == "POST":
        if form.is_valid():
            form.save()
            return empty_success
        else:
            return JsonResponse({"error": form.errors}, status=400)
    
    return bad_request


def add_file(request):
    if not request.user or not request.user.is_authenticated:
        return authentication_error

    if request.is_ajax and request.method == "POST":
        form = FileForm(request.POST, request.FILES)
        form.instance.name = 'placeholder'
        if form.is_valid():
            file = form.save(commit=False)
            if file.parent.owner != request.user:
                return forbidden
            
            file.owner = request.user
            # file.date_created = os.path.getmtime(file.file_object.path)
            file.name = file.file_object.name
            try:
                file.save()
            except IntegrityError:
                return server_error
            
            sections = create_sections(file)
            Section.objects.bulk_create(sections)
            prover = request.session.get('prover', 'alt-ergo')
            conditions = request.session.get('conditions', [])
            update_frama_output(file, prover, conditions)

            return empty_success
        else:
            return JsonResponse({"error": form.errors}, status=400)

    return bad_request



def delete_node(request):
    if not request.user or not request.user.is_authenticated:
        return authentication_error
        
    if request.is_ajax and request.method == 'POST':
        form = DeletionForm(request.POST)
        if form.is_valid():
            files = request.POST.getlist('files')
            dirs = request.POST.getlist('directories')
            for f in files:
                file = File.objects.get(name=f)
                file.remove()
            for d in dirs:
                dir = Directory.objects.get(name=d)
                dir.remove()
            return empty_success
        else:
            return JsonResponse({"error": form.errors}, status=400)

    return bad_request


def change_prover(request):
    prover = request.POST['prover']
    request.session['prover'] = prover
    print('prover changed to ' + request.session['prover'])
    return empty_success

def change_vcs(request):
    new_vcs = dict(request.POST).get('conditions', [])
    request.session['vcs'] = new_vcs
    print('New verification conditions:')
    print(request.session['vcs'])
    return empty_success

def run_frama(request):
    file_pk = request.GET.get('file')
    print(file_pk)
    if not file_pk:
        return not_found
    try:
        file = File.objects.get(pk=file_pk)
    except:
        return not_found

    prover = request.session.get('prover', '')
    conditions = request.session.get('vcs', [])
    
    update_frama_output(file, prover, conditions)
    
    file = File.objects.get(pk=file_pk)
    sections_arr = []
    file_sections = file.section_set.all()

    for section in file_sections:
        if section.status_data and section.status_data.data:
            sections_arr.append({
                "name": section.name,
                "data": section.status_data.data,
                "key": section.pk,
                "color": section.status
            })

    body = {'sections': sections_arr, 'logs': file.frama_output}
    return JsonResponse(body, status=200)

def login_page(request):
    return render(request, 'frama_app/login.html')

def logout_user(request):
    logout(request)
    # url = request.build_absolute_uri('/frama_app/login')
    return empty_success

def auth(request):
    username = request.POST.get('username')
    password = request.POST.get('password')

    if username is None or password is None:
        return HttpResponseRedirect('/frama_app/login')

    print(username, password)

    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)

        return HttpResponseRedirect(('/frama_app/index'))
    else:
        return HttpResponseRedirect('/frama_app/login')



def get_filetree(request):
    if not request.user.is_authenticated:
        return authentication_error

    if request.is_ajax and request.method == 'GET':
        entities = []

        for file in File.objects.filter(exists=True, owner = request.user):
            # if file.exists and file.owner == request.user:
            entities.append({
                "id": "fil" + str(file.pk),
                "parent": "#" if file.parent is None else "dir" + str(file.parent.pk),
                "text": file.name,
            })

        for directory in Directory.objects.filter(exists=True, owner = request.user):
            # if directory.available and directory.owner == request.user:
            entities.append({
                "id": "dir" + str(directory.pk),
                "parent": "#" if directory.parent is None else "dir" + str(directory.parent.pk),
                "text": directory.name,
            })

        print(entities)

        return JsonResponse(entities, status=200, safe=False)

    return bad_request



def get_file(request):
    if not request.user.is_authenticated:
        return authentication_error

    if request.is_ajax and request.method == 'GET':
        file_pk = request.GET.get('file')
        
        if file_pk is None or not file_pk.isnumeric():
            return not_found

        file = File.objects.filter(pk=file_pk).first()

        if file is None or not file.exists or file.owner != request.user:
            return not_found

        file_sections_arr = []

        file_sections = file.section_set.all()

        for section in file_sections:
            if section.status_data and section.status_data.data:
                file_sections_arr.append({
                    "name": section.name,
                    "data": section.status_data.data,
                    "key": section.pk,
                    "color": section.status
                })
        
        filecontent = file.file_object.read().decode()

        file_dict = {
            "source_code": filecontent, 
            "name": file.name, 
            "sections": file_sections_arr,
            "logs": file.frama_output 
        }
        return JsonResponse(file_dict, status=200)

    return bad_request

frama_app/templates/frama_app/filetree.html
<li>
    {% if dir %}
    {{dir.name}}
    {% endif %}
        <ul>
            {%for file in files %}
                {% if file.parent == dir %}
                    <li id="{{file.name}}">
                        {% firstof request.GET.tab "0" as tab_value %}
                        <a href="{% url 'frama_app:file' file.name tab_value %}"><button>{{ file.name }}</button></a>
                    </li>
                {% endif %}
            {%endfor%}
        </ul>
    <ul>
     {%for node in directories %}
         {% if node.parent == dir %}
          {%with dir=node template_name="frama_app/filetree.html" %}
               {%include template_name%}
          {%endwith%}
         {% endif %}
     {%endfor%}
     </ul>
</li>

frama_app/templates/frama_app/index.html
{% csrf_token %}
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jstree/3.2.1/themes/default/style.min.css" />

	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jstree/3.2.1/jstree.min.js"></script>
	
	<title>Assignment AWWW</title>
	
    <link rel="stylesheet" type="text/css" href="{% static 'frama_app/styles.css' %}">
	<script>
		const url_get_filesystem_tree = "{% url 'frama_app:get_filetree' %}";
		const url_get_file = "{% url 'frama_app:file' %}";
		const url_add_file = "{% url 'frama_app:add_file' %}";
		const url_add_dir = "{% url 'frama_app:add_dir' %}";
		const url_delete = "{% url 'frama_app:delete_node' %}";
		const url_logout = "{% url 'frama_app:logout' %}";
		const url_run = "{% url 'frama_app:run' %}"
		const url_provers = "{% url 'frama_app:prover' %}"
		const url_vcs = "{% url 'frama_app:vcs' %}"
	</script>

	<script src="{% static 'frama_app/main.js' %}?{% now 'U' %}" type="text/javascript"></script>
</head>

<body>
	<div id="add-file-modal" class="modal">
		<form class="addDeleteForm" id="add-file-form" method="POST" enctype="multipart/form-data">
			<h1>Add file</h1>
			<!-- {% csrf_token %} -->
			{{add_file_form}}
			<br>
			<input type="submit"/>
		</form>		
	</div>
	<div id="add-dir-modal" class="modal">
		<form class="addDeleteForm" id="add-dir-form" method="POST">
			<h1>Add directory</h1>
			<!-- {% csrf_token %} -->
			{{add_dir_form}}
			<br>
			<input type="submit"/>
		</form>
	</div>
	<div id="delete-modal" class="modal">
		<form class="addDeleteForm" id="delete-form"  method="POST">
			<h1>Files and directories to delete</h1>
			<!-- {% csrf_token %} -->
			{{delete_form}}
			</br>
			<input type="submit" value="Delete"/>
		</form>
	</div>
	
	<div class="main-grid">
		<div class="menu-bar">
			<div id="left-buttons">
				<button id="add-dir-btn">Add Directory</button>
				<button id="add-file-btn">Add File</button>
				<button id="delete-btn">Delete file/directory</button>
			</div>
			<div id="right-buttons">
				<button id="run-btn">Run Configuration</button>
				<button id="logout-btn">Logout</button>
			</div>
		
		</div>
		<div class="file-select">
			<h1>Files:</h1>
			<div id="filesystem_tree"></div>
		</div>
		<div class="file-content">
			<pre id="file-text-content">Please select a file to open</pre>
		</div>
		
		<div id="program-elements"></div>
		
		<div class="tabs">
			<div class="tab-list">
				<div class="tab"><button id="tab1-btn" onclick="openTab(event, 1)">PROVERS</button></div>
				<div class="tab"><button id="tab2-btn" onclick="openTab(event, 2)">VCs</button></div>
				<div class="tab"><button id="tab3-btn" onclick="openTab(event, 3)">RESULT</button></div>
			</div>
			<div class="tab-content">
					<div class="tab-form" id="tab1">
						<form id="prover-form" method="POST">
							{% csrf_token %}
							{{provers_form}}
							<input type="submit" id="prover-submit"/>
						</form>
					</div>
					<div class="tab-form" id="tab2">
						<form id="vcs-form" method="POST">
							{% csrf_token %}
							{{vcs_form}}
							<input type="submit" id="vcs-submit"/>
						</form>
					</div>
					<div id="tab3">
						<pre id="result"></pre>
					</div>
			</div>
		</div>
	</div>

</body>

</html>

frama_app/templates/frama_app/login.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Login</title>
    </head>
    <body>
        <form action="{% url 'frama_app:auth' %}" method="POST">
            {% csrf_token %}
            <label for="username">Login:</label>
            <input type="text" name="username" id="username">
            <label for="password">Password:</label>
            <input type="password" name="password" id="password">
            <button type="submit">Log in</button>
        </form>
    </body>

</html>